<?php

namespace ContainerOv3v1PJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_E7BWt22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.E7BWt22' shared service.
     *
     * @return \App\Entity\NatureSalarieContrat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ApiController::api_getdureecontrat()": the $natureContrat argument is type-hinted with the non-existent class or interface: "App\\Entity\\NatureSalarieContrat".');
    }
}
