<?php

namespace ContainerOv3v1PJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ys_JvjUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ys.JvjU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ys.JvjU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'natureContrat' => ['privates', '.errored.E7BWt22', NULL, 'Cannot determine controller argument for "App\\Controller\\ApiController::api_getdureecontrat()": the $natureContrat argument is type-hinted with the non-existent class or interface: "App\\Entity\\NatureSalarieContrat".'],
        ], [
            'natureContrat' => '?',
        ]);
    }
}
