<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Periode extends \App\Entity\Periode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'arretTravailLgs', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'bulletins', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'problemes', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'bordereaus'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'date', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'arretTravailLgs', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'bulletins', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'problemes', '' . "\0" . 'App\\Entity\\Periode' . "\0" . 'bordereaus'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Periode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation', []);

        return parent::getAbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation(?string $abreviation): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation', [$abreviation]);

        return parent::setAbreviation($abreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', []);

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate(?\DateTimeInterface $date): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', [$date]);

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getArretTravailLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArretTravailLgs', []);

        return parent::getArretTravailLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addArretTravailLg(\App\Entity\PArretTravailLg $arretTravailLg): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArretTravailLg', [$arretTravailLg]);

        return parent::addArretTravailLg($arretTravailLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArretTravailLg(\App\Entity\PArretTravailLg $arretTravailLg): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArretTravailLg', [$arretTravailLg]);

        return parent::removeArretTravailLg($arretTravailLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getElementEcheances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElementEcheances', []);

        return parent::getElementEcheances();
    }

    /**
     * {@inheritDoc}
     */
    public function addElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElementEcheance', [$elementEcheance]);

        return parent::addElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElementEcheance', [$elementEcheance]);

        return parent::removeElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function getBulletins(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBulletins', []);

        return parent::getBulletins();
    }

    /**
     * {@inheritDoc}
     */
    public function addBulletin(\App\Entity\Tbulletin $bulletin): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBulletin', [$bulletin]);

        return parent::addBulletin($bulletin);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBulletin(\App\Entity\Tbulletin $bulletin): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBulletin', [$bulletin]);

        return parent::removeBulletin($bulletin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrelevementLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrelevementLgs', []);

        return parent::getPrelevementLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrelevementLg(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrelevementLg', [$prelevementLg]);

        return parent::addPrelevementLg($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrelevementLg(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrelevementLg', [$prelevementLg]);

        return parent::removePrelevementLg($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getProblemes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProblemes', []);

        return parent::getProblemes();
    }

    /**
     * {@inheritDoc}
     */
    public function addProbleme(\App\Entity\Probleme $probleme): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProbleme', [$probleme]);

        return parent::addProbleme($probleme);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProbleme(\App\Entity\Probleme $probleme): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProbleme', [$probleme]);

        return parent::removeProbleme($probleme);
    }

    /**
     * {@inheritDoc}
     */
    public function getBordereaus(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBordereaus', []);

        return parent::getBordereaus();
    }

    /**
     * {@inheritDoc}
     */
    public function addBordereau(\App\Entity\PBordereau $bordereau): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBordereau', [$bordereau]);

        return parent::addBordereau($bordereau);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBordereau(\App\Entity\PBordereau $bordereau): \App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBordereau', [$bordereau]);

        return parent::removeBordereau($bordereau);
    }

}
