<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tbulletin extends \App\Entity\Tbulletin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'Annee', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'periode', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'bulletinLgs', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'contract', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'devise', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'bordereau', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'journalBulletinLgs'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'Annee', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'periode', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'bulletinLgs', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'contract', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'devise', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'observation', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'bordereau', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\Tbulletin' . "\0" . 'journalBulletinLgs'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tbulletin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getAnnee(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnnee', []);

        return parent::getAnnee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnnee(int $Annee): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnnee', [$Annee]);

        return parent::setAnnee($Annee);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeriode(): ?\App\Entity\Periode
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeriode', []);

        return parent::getPeriode();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeriode(?\App\Entity\Periode $periode): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeriode', [$periode]);

        return parent::setPeriode($periode);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrelevements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrelevements', []);

        return parent::getPrelevements();
    }

    /**
     * {@inheritDoc}
     */
    public function getBulletinLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBulletinLgs', []);

        return parent::getBulletinLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveBulletinLgs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveBulletinLgs', []);

        return parent::getActiveBulletinLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrelevement(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrelevement', [$prelevementLg]);

        return parent::addPrelevement($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrelevement(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrelevement', [$prelevementLg]);

        return parent::removePrelevement($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getContract(): ?\App\Entity\LContract
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract(?\App\Entity\LContract $contract): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getElementEcheances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElementEcheances', []);

        return parent::getElementEcheances();
    }

    /**
     * {@inheritDoc}
     */
    public function addElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElementEcheance', [$elementEcheance]);

        return parent::addElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElementEcheance', [$elementEcheance]);

        return parent::removeElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossier(): ?\App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossier', []);

        return parent::getDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDossier(?\App\Entity\PDossier $dossier): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDossier', [$dossier]);

        return parent::setDossier($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getDevise(): ?\App\Entity\PDevise
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDevise', []);

        return parent::getDevise();
    }

    /**
     * {@inheritDoc}
     */
    public function setDevise(?\App\Entity\PDevise $devise): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDevise', [$devise]);

        return parent::setDevise($devise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement(): ?\App\Entity\PPaiement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', []);

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement(?\App\Entity\PPaiement $paiement): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', [$paiement]);

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation(?string $observation): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$observation]);

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getBordereau(): ?\App\Entity\PBordereau
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBordereau', []);

        return parent::getBordereau();
    }

    /**
     * {@inheritDoc}
     */
    public function setBordereau(?\App\Entity\PBordereau $bordereau): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBordereau', [$bordereau]);

        return parent::setBordereau($bordereau);
    }

    /**
     * {@inheritDoc}
     */
    public function getPPiece(): ?\App\Entity\PPiece
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPPiece', []);

        return parent::getPPiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setPPiece(?\App\Entity\PPiece $piece): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPPiece', [$piece]);

        return parent::setPPiece($piece);
    }

    /**
     * {@inheritDoc}
     */
    public function getJournalBulletinLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournalBulletinLgs', []);

        return parent::getJournalBulletinLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addJournalBulletinLg(\App\Entity\JournalBulletinLg $journalBulletinLg): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJournalBulletinLg', [$journalBulletinLg]);

        return parent::addJournalBulletinLg($journalBulletinLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJournalBulletinLg(\App\Entity\JournalBulletinLg $journalBulletinLg): \App\Entity\Tbulletin
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJournalBulletinLg', [$journalBulletinLg]);

        return parent::removeJournalBulletinLg($journalBulletinLg);
    }

}
