<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PDossier extends \App\Entity\PDossier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'contracts', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'bulletins', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'groupement', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'DossierUgouvId', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviation2', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviationUgouv', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'fcy0', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'cpy0', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'partenaireId'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviation', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'contracts', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'bulletins', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'groupement', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'DossierUgouvId', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviation2', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'abreviationUgouv', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'fcy0', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'cpy0', '' . "\0" . 'App\\Entity\\PDossier' . "\0" . 'partenaireId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PDossier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(string $Designation): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$Designation]);

        return parent::setDesignation($Designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation', []);

        return parent::getAbreviation();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation(string $Abreviation): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation', [$Abreviation]);

        return parent::setAbreviation($Abreviation);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getContracts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContracts', []);

        return parent::getContracts();
    }

    /**
     * {@inheritDoc}
     */
    public function getActiveContracts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActiveContracts', []);

        return parent::getActiveContracts();
    }

    /**
     * {@inheritDoc}
     */
    public function addContract(\App\Entity\LContract $contract): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addContract', [$contract]);

        return parent::addContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function removeContract(\App\Entity\LContract $contract): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeContract', [$contract]);

        return parent::removeContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getBulletins(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBulletins', []);

        return parent::getBulletins();
    }

    /**
     * {@inheritDoc}
     */
    public function addBulletin(\App\Entity\Tbulletin $bulletin): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBulletin', [$bulletin]);

        return parent::addBulletin($bulletin);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBulletin(\App\Entity\Tbulletin $bulletin): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBulletin', [$bulletin]);

        return parent::removeBulletin($bulletin);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupement', []);

        return parent::getGroupement();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupement(?string $groupement): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupement', [$groupement]);

        return parent::setGroupement($groupement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossierUgouvId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossierUgouvId', []);

        return parent::getDossierUgouvId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDossierUgouvId(?int $DossierUgouvId): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDossierUgouvId', [$DossierUgouvId]);

        return parent::setDossierUgouvId($DossierUgouvId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviation2(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviation2', []);

        return parent::getAbreviation2();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviation2(?string $abreviation2): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviation2', [$abreviation2]);

        return parent::setAbreviation2($abreviation2);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbreviationUgouv(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbreviationUgouv', []);

        return parent::getAbreviationUgouv();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbreviationUgouv(?string $AbreviationUgouv): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbreviationUgouv', [$AbreviationUgouv]);

        return parent::setAbreviationUgouv($AbreviationUgouv);
    }

    /**
     * {@inheritDoc}
     */
    public function getFcy0(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFcy0', []);

        return parent::getFcy0();
    }

    /**
     * {@inheritDoc}
     */
    public function setFcy0(?string $fcy0): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFcy0', [$fcy0]);

        return parent::setFcy0($fcy0);
    }

    /**
     * {@inheritDoc}
     */
    public function getCpy0(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCpy0', []);

        return parent::getCpy0();
    }

    /**
     * {@inheritDoc}
     */
    public function setCpy0(?string $cpy0): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCpy0', [$cpy0]);

        return parent::setCpy0($cpy0);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartenaireId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartenaireId', []);

        return parent::getPartenaireId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartenaireId(?int $partenaireId): \App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartenaireId', [$partenaireId]);

        return parent::setPartenaireId($partenaireId);
    }

}
