<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class PPrelevement extends \App\Entity\PPrelevement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'contract', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'rubrique', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'created', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'nombreMois', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'active', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'valider', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'montantEcheance', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'motif'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'id', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'contract', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'rubrique', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'created', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'montant', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'dateDebut', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'nombreMois', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'active', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'valider', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'prelevementLgs', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'dossier', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'userCreated', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'montantEcheance', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'code', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'piece', '' . "\0" . 'App\\Entity\\PPrelevement' . "\0" . 'motif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (PPrelevement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getContract(): ?\App\Entity\LContract
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContract', []);

        return parent::getContract();
    }

    /**
     * {@inheritDoc}
     */
    public function setContract(?\App\Entity\LContract $contract): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContract', [$contract]);

        return parent::setContract($contract);
    }

    /**
     * {@inheritDoc}
     */
    public function getRubrique(): ?\App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRubrique', []);

        return parent::getRubrique();
    }

    /**
     * {@inheritDoc}
     */
    public function setRubrique(?\App\Entity\Prubrique $rubrique): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRubrique', [$rubrique]);

        return parent::setRubrique($rubrique);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated(?\DateTimeInterface $created): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontant(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontant', []);

        return parent::getMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontant(?float $montant): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontant', [$montant]);

        return parent::setMontant($montant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut(?\DateTimeInterface $dateDebut): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getNombreMois(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNombreMois', []);

        return parent::getNombreMois();
    }

    /**
     * {@inheritDoc}
     */
    public function setNombreMois(?float $nombreMois): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNombreMois', [$nombreMois]);

        return parent::setNombreMois($nombreMois);
    }

    /**
     * {@inheritDoc}
     */
    public function isActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isActive', []);

        return parent::isActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(?bool $active): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function isValider(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isValider', []);

        return parent::isValider();
    }

    /**
     * {@inheritDoc}
     */
    public function setValider(?bool $valider): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValider', [$valider]);

        return parent::setValider($valider);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrelevementLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrelevementLgs', []);

        return parent::getPrelevementLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrelevementLg(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrelevementLg', [$prelevementLg]);

        return parent::addPrelevementLg($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrelevementLg(\App\Entity\PPrelevementLg $prelevementLg): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrelevementLg', [$prelevementLg]);

        return parent::removePrelevementLg($prelevementLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getDossier(): ?\App\Entity\PDossier
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDossier', []);

        return parent::getDossier();
    }

    /**
     * {@inheritDoc}
     */
    public function setDossier(?\App\Entity\PDossier $dossier): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDossier', [$dossier]);

        return parent::setDossier($dossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreated(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreated', []);

        return parent::getUserCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreated(?\App\Entity\Users $userCreated): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreated', [$userCreated]);

        return parent::setUserCreated($userCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantEcheance(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantEcheance', []);

        return parent::getMontantEcheance();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantEcheance(?float $montantEcheance): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantEcheance', [$montantEcheance]);

        return parent::setMontantEcheance($montantEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPiece(): ?\App\Entity\PPiece
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPiece', []);

        return parent::getPiece();
    }

    /**
     * {@inheritDoc}
     */
    public function setPiece(?\App\Entity\PPiece $piece): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPiece', [$piece]);

        return parent::setPiece($piece);
    }

    /**
     * {@inheritDoc}
     */
    public function getMotif(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMotif', []);

        return parent::getMotif();
    }

    /**
     * {@inheritDoc}
     */
    public function setMotif(?string $motif): \App\Entity\PPrelevement
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMotif', [$motif]);

        return parent::setMotif($motif);
    }

}
