<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prubrique extends \App\Entity\Prubrique implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'lelementFixes', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'PbaremeBrutes', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'facture', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'fournisseur', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'idArticle', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'matrices', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'bulletinLgs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'baremeCimrs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'prelevements', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'honoraire', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'indeminite', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'prets', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'sens', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'absence', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'compteComptables', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'journal', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'flagInput', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'siteId', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'journalBulletinLgs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'partenaireId', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'regulArticleUgouvId'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'lelementFixes', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'PbaremeBrutes', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'facture', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'paiement', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'fournisseur', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'idArticle', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'elementEcheances', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'matrices', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'bulletinLgs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'baremeCimrs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'prelevements', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'honoraire', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'indeminite', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'prets', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'sens', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'absence', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'fixe', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'compteComptables', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'journal', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'flagInput', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'siteId', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'journalBulletinLgs', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'partenaireId', '' . "\0" . 'App\\Entity\\Prubrique' . "\0" . 'regulArticleUgouvId'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prubrique $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(string $code): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(string $Designation): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$Designation]);

        return parent::setDesignation($Designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getLelementFixes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLelementFixes', []);

        return parent::getLelementFixes();
    }

    /**
     * {@inheritDoc}
     */
    public function addLelementFix(\App\Entity\LelementFixe $lelementFix): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLelementFix', [$lelementFix]);

        return parent::addLelementFix($lelementFix);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLelementFix(\App\Entity\LelementFixe $lelementFix): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLelementFix', [$lelementFix]);

        return parent::removeLelementFix($lelementFix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPbaremeBrutes(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPbaremeBrutes', []);

        return parent::getPbaremeBrutes();
    }

    /**
     * {@inheritDoc}
     */
    public function addPbaremeBrute(\App\Entity\PbaremeBrute $PbaremeBrute): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPbaremeBrute', [$PbaremeBrute]);

        return parent::addPbaremeBrute($PbaremeBrute);
    }

    /**
     * {@inheritDoc}
     */
    public function removePbaremeBrute(\App\Entity\PbaremeBrute $PbaremeBrute): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePbaremeBrute', [$PbaremeBrute]);

        return parent::removePbaremeBrute($PbaremeBrute);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(int $facture): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaiement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaiement', []);

        return parent::getPaiement();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaiement(int $paiement): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaiement', [$paiement]);

        return parent::setPaiement($paiement);
    }

    /**
     * {@inheritDoc}
     */
    public function getFournisseur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFournisseur', []);

        return parent::getFournisseur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFournisseur(string $fournisseur): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFournisseur', [$fournisseur]);

        return parent::setFournisseur($fournisseur);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdArticle(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdArticle', []);

        return parent::getIdArticle();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdArticle(int $idArticle): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdArticle', [$idArticle]);

        return parent::setIdArticle($idArticle);
    }

    /**
     * {@inheritDoc}
     */
    public function getElementEcheances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getElementEcheances', []);

        return parent::getElementEcheances();
    }

    /**
     * {@inheritDoc}
     */
    public function addElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addElementEcheance', [$elementEcheance]);

        return parent::addElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeElementEcheance(\App\Entity\LElementEcheance $elementEcheance): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeElementEcheance', [$elementEcheance]);

        return parent::removeElementEcheance($elementEcheance);
    }

    /**
     * {@inheritDoc}
     */
    public function getMatrices(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMatrices', []);

        return parent::getMatrices();
    }

    /**
     * {@inheritDoc}
     */
    public function addMatrix(\App\Entity\VMatrix $matrix): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMatrix', [$matrix]);

        return parent::addMatrix($matrix);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMatrix(\App\Entity\VMatrix $matrix): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMatrix', [$matrix]);

        return parent::removeMatrix($matrix);
    }

    /**
     * {@inheritDoc}
     */
    public function getBulletinLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBulletinLgs', []);

        return parent::getBulletinLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBulletinLg(\App\Entity\TbulletinLg $bulletinLg): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBulletinLg', [$bulletinLg]);

        return parent::addBulletinLg($bulletinLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBulletinLg(\App\Entity\TbulletinLg $bulletinLg): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBulletinLg', [$bulletinLg]);

        return parent::removeBulletinLg($bulletinLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getBaremeCimrs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBaremeCimrs', []);

        return parent::getBaremeCimrs();
    }

    /**
     * {@inheritDoc}
     */
    public function addBaremeCimr(\App\Entity\PBaremeCimr $baremeCimr): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addBaremeCimr', [$baremeCimr]);

        return parent::addBaremeCimr($baremeCimr);
    }

    /**
     * {@inheritDoc}
     */
    public function removeBaremeCimr(\App\Entity\PBaremeCimr $baremeCimr): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeBaremeCimr', [$baremeCimr]);

        return parent::removeBaremeCimr($baremeCimr);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrelevements(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrelevements', []);

        return parent::getPrelevements();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrelevement(\App\Entity\PPrelevement $prelevement): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrelevement', [$prelevement]);

        return parent::addPrelevement($prelevement);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrelevement(\App\Entity\PPrelevement $prelevement): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrelevement', [$prelevement]);

        return parent::removePrelevement($prelevement);
    }

    /**
     * {@inheritDoc}
     */
    public function isHonoraire(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isHonoraire', []);

        return parent::isHonoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setHonoraire(?bool $honoraire): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHonoraire', [$honoraire]);

        return parent::setHonoraire($honoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function isIndeminite(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIndeminite', []);

        return parent::isIndeminite();
    }

    /**
     * {@inheritDoc}
     */
    public function setIndeminite(?bool $indeminite): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIndeminite', [$indeminite]);

        return parent::setIndeminite($indeminite);
    }

    /**
     * {@inheritDoc}
     */
    public function isPrets(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPrets', []);

        return parent::isPrets();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrets(?bool $prets): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrets', [$prets]);

        return parent::setPrets($prets);
    }

    /**
     * {@inheritDoc}
     */
    public function getSens(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSens', []);

        return parent::getSens();
    }

    /**
     * {@inheritDoc}
     */
    public function setSens(?float $sens): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSens', [$sens]);

        return parent::setSens($sens);
    }

    /**
     * {@inheritDoc}
     */
    public function isAbsence(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAbsence', []);

        return parent::isAbsence();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbsence(?bool $absence): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbsence', [$absence]);

        return parent::setAbsence($absence);
    }

    /**
     * {@inheritDoc}
     */
    public function isFixe(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFixe', []);

        return parent::isFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFixe(?bool $fixe): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFixe', [$fixe]);

        return parent::setFixe($fixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getCompteComptables(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCompteComptables', []);

        return parent::getCompteComptables();
    }

    /**
     * {@inheritDoc}
     */
    public function addCompteComptable(\App\Entity\PCompteComptable $compteComptable): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCompteComptable', [$compteComptable]);

        return parent::addCompteComptable($compteComptable);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCompteComptable(\App\Entity\PCompteComptable $compteComptable): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCompteComptable', [$compteComptable]);

        return parent::removeCompteComptable($compteComptable);
    }

    /**
     * {@inheritDoc}
     */
    public function isJournal(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isJournal', []);

        return parent::isJournal();
    }

    /**
     * {@inheritDoc}
     */
    public function setJournal(?bool $journal): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJournal', [$journal]);

        return parent::setJournal($journal);
    }

    /**
     * {@inheritDoc}
     */
    public function isFlagInput(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isFlagInput', []);

        return parent::isFlagInput();
    }

    /**
     * {@inheritDoc}
     */
    public function setFlagInput(?bool $flagInput): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFlagInput', [$flagInput]);

        return parent::setFlagInput($flagInput);
    }

    /**
     * {@inheritDoc}
     */
    public function getSiteId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSiteId', []);

        return parent::getSiteId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSiteId(?int $siteId): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSiteId', [$siteId]);

        return parent::setSiteId($siteId);
    }

    /**
     * {@inheritDoc}
     */
    public function getJournalBulletinLgs(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJournalBulletinLgs', []);

        return parent::getJournalBulletinLgs();
    }

    /**
     * {@inheritDoc}
     */
    public function addJournalBulletinLg(\App\Entity\JournalBulletinLg $journalBulletinLg): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addJournalBulletinLg', [$journalBulletinLg]);

        return parent::addJournalBulletinLg($journalBulletinLg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeJournalBulletinLg(\App\Entity\JournalBulletinLg $journalBulletinLg): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeJournalBulletinLg', [$journalBulletinLg]);

        return parent::removeJournalBulletinLg($journalBulletinLg);
    }

    /**
     * {@inheritDoc}
     */
    public function getPartenaireId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPartenaireId', []);

        return parent::getPartenaireId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPartenaireId(?int $partenaireId): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPartenaireId', [$partenaireId]);

        return parent::setPartenaireId($partenaireId);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegulArticleUgouvId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegulArticleUgouvId', []);

        return parent::getRegulArticleUgouvId();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegulArticleUgouvId(?int $RegulArticleUgouvId): \App\Entity\Prubrique
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegulArticleUgouvId', [$RegulArticleUgouvId]);

        return parent::setRegulArticleUgouvId($RegulArticleUgouvId);
    }

}
