<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class UsOperation extends \App\Entity\UsOperation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'sousModule', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'link', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'icon', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'classTag', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'idTag', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'ordre', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'userOperationDossiers', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'align'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'id', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'sousModule', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'link', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'icon', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'designation', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'classTag', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'idTag', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'ordre', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'userOperationDossiers', '' . "\0" . 'App\\Entity\\UsOperation' . "\0" . 'align'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (UsOperation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function gztUserOperationDossiers(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'gztUserOperationDossiers', []);

        return parent::gztUserOperationDossiers();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getSousModule(): ?\App\Entity\UsSousModule
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSousModule', []);

        return parent::getSousModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setSousModule(?\App\Entity\UsSousModule $sousModule): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSousModule', [$sousModule]);

        return parent::setSousModule($sousModule);
    }

    /**
     * {@inheritDoc}
     */
    public function getLink(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLink', []);

        return parent::getLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setLink(?string $link): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLink', [$link]);

        return parent::setLink($link);
    }

    /**
     * {@inheritDoc}
     */
    public function getIcon(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIcon', []);

        return parent::getIcon();
    }

    /**
     * {@inheritDoc}
     */
    public function setIcon(?string $icon): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIcon', [$icon]);

        return parent::setIcon($icon);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignation', []);

        return parent::getDesignation();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignation(?string $designation): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignation', [$designation]);

        return parent::setDesignation($designation);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassTag(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassTag', []);

        return parent::getClassTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassTag(?string $classTag): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassTag', [$classTag]);

        return parent::setClassTag($classTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTag(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTag', []);

        return parent::getIdTag();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTag(?string $idTag): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTag', [$idTag]);

        return parent::setIdTag($idTag);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdre(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdre', []);

        return parent::getOrdre();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrdre(?int $ordre): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrdre', [$ordre]);

        return parent::setOrdre($ordre);
    }

    /**
     * {@inheritDoc}
     */
    public function isAlign(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAlign', []);

        return parent::isAlign();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlign(?bool $align): \App\Entity\UsOperation
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlign', [$align]);

        return parent::setAlign($align);
    }

}
