# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api_input: https://172.20.0.240:8000/
    ugouv: https://localhost:8001/
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Service\CalculPaieService:
        class: App\Service\CalculPaieService
        arguments: ['@doctrine.orm.entity_manager']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\EventListener\JournalPaieListener:
        arguments: 
            - '@Doctrine\ORM\EntityManagerInterface'
        tags:
            - { name: kernel.event_listener, event: kernel.terminate, method: 'onKernelTerminate' }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
