<?php

namespace ContainerMgXxIJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5wK8C1vService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5wK8C1v' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5wK8C1v'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bulletin' => ['privates', '.errored..service_locator.5wK8C1v.App\\Entity\\Tbulletin', NULL, 'Cannot autowire service ".service_locator.5wK8C1v": it references class "App\\Entity\\Tbulletin" but no such service exists.'],
        ], [
            'bulletin' => 'App\\Entity\\Tbulletin',
        ]);
    }
}
