<?php

namespace ContainerMgXxIJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N1fQ1siService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.N1fQ1si' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.N1fQ1si'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'prelevement' => ['privates', '.errored..service_locator.N1fQ1si.App\\Entity\\PPrelevement', NULL, 'Cannot autowire service ".service_locator.N1fQ1si": it references class "App\\Entity\\PPrelevement" but no such service exists.'],
        ], [
            'prelevement' => 'App\\Entity\\PPrelevement',
        ]);
    }
}
