<?php

namespace ContainerMgXxIJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLelementFixeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m6Dc8CE.App\Entity\LelementFixe' shared service.
     *
     * @return \App\Entity\LelementFixe
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m6Dc8CE": it references class "App\\Entity\\LelementFixe" but no such service exists.');
    }
}
