<?php

namespace ContainerMgXxIJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPDossier2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Rp_LayS.App\Entity\PDossier' shared service.
     *
     * @return \App\Entity\PDossier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Rp_LayS": it references class "App\\Entity\\PDossier" but no such service exists.');
    }
}
