<?php

namespace ContainerMgXxIJj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTbulletinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5wK8C1v.App\Entity\Tbulletin' shared service.
     *
     * @return \App\Entity\Tbulletin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5wK8C1v": it references class "App\\Entity\\Tbulletin" but no such service exists.');
    }
}
