<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O4ZaYkfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O4ZaYkf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O4ZaYkf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bareme' => ['privates', '.errored..service_locator.O4ZaYkf.App\\Entity\\Pbareme', NULL, 'Cannot autowire service ".service_locator.O4ZaYkf": it references class "App\\Entity\\Pbareme" but no such service exists.'],
        ], [
            'bareme' => 'App\\Entity\\Pbareme',
        ]);
    }
}
