<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Et5xeWvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Et5xeWv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Et5xeWv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossierId' => ['privates', '.errored..service_locator.Et5xeWv.App\\Entity\\PDossier', NULL, 'Cannot autowire service ".service_locator.Et5xeWv": it references class "App\\Entity\\PDossier" but no such service exists.'],
            'operation' => ['privates', '.errored..service_locator.Et5xeWv.App\\Entity\\UsOperation', NULL, 'Cannot autowire service ".service_locator.Et5xeWv": it references class "App\\Entity\\UsOperation" but no such service exists.'],
            'userId' => ['privates', '.errored..service_locator.Et5xeWv.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.Et5xeWv": it references class "App\\Entity\\Users" but no such service exists.'],
        ], [
            'dossierId' => 'App\\Entity\\PDossier',
            'operation' => 'App\\Entity\\UsOperation',
            'userId' => 'App\\Entity\\Users',
        ]);
    }
}
