<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPnatureContractService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.xl2tnEQ.App\Entity\PnatureContract' shared service.
     *
     * @return \App\Entity\PnatureContract
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.xl2tnEQ": it references class "App\\Entity\\PnatureContract" but no such service exists.');
    }
}
