<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPPaiementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.lxTOdT8.App\Entity\PPaiement' shared service.
     *
     * @return \App\Entity\PPaiement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.lxTOdT8": it references class "App\\Entity\\PPaiement" but no such service exists.');
    }
}
