<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPPrelevementService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.N1fQ1si.App\Entity\PPrelevement' shared service.
     *
     * @return \App\Entity\PPrelevement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.N1fQ1si": it references class "App\\Entity\\PPrelevement" but no such service exists.');
    }
}
