<?php

namespace ContainerPuCmYNF;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsOperationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Et5xeWv.App\Entity\UsOperation' shared service.
     *
     * @return \App\Entity\UsOperation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Et5xeWv": it references class "App\\Entity\\UsOperation" but no such service exists.');
    }
}
