<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QEqknXZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qEqknXZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qEqknXZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossier' => ['privates', '.errored..service_locator.qEqknXZ.App\\Entity\\PDossier', NULL, 'Cannot autowire service ".service_locator.qEqknXZ": it references class "App\\Entity\\PDossier" but no such service exists.'],
            'user' => ['privates', '.errored..service_locator.qEqknXZ.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.qEqknXZ": it references class "App\\Entity\\Users" but no such service exists.'],
        ], [
            'dossier' => 'App\\Entity\\PDossier',
            'user' => 'App\\Entity\\Users',
        ]);
    }
}
