<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LxTOdT8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lxTOdT8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lxTOdT8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossier' => ['privates', '.errored..service_locator.lxTOdT8.App\\Entity\\PDossier', NULL, 'Cannot autowire service ".service_locator.lxTOdT8": it references class "App\\Entity\\PDossier" but no such service exists.'],
            'paiement' => ['privates', '.errored..service_locator.lxTOdT8.App\\Entity\\PPaiement', NULL, 'Cannot autowire service ".service_locator.lxTOdT8": it references class "App\\Entity\\PPaiement" but no such service exists.'],
        ], [
            'dossier' => 'App\\Entity\\PDossier',
            'paiement' => 'App\\Entity\\PPaiement',
        ]);
    }
}
