<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCalculPaieServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\CalculPaieService' shared autowired service.
     *
     * @return \App\Service\CalculPaieService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'CalculPaieService.php';

        return $container->privates['App\\Service\\CalculPaieService'] = new \App\Service\CalculPaieService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()));
    }
}
