<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLContractService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.5sUk8rT.App\Entity\LContract' shared service.
     *
     * @return \App\Entity\LContract
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.5sUk8rT": it references class "App\\Entity\\LContract" but no such service exists.');
    }
}
