<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPbaremeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.O4ZaYkf.App\Entity\Pbareme' shared service.
     *
     * @return \App\Entity\Pbareme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.O4ZaYkf": it references class "App\\Entity\\Pbareme" but no such service exists.');
    }
}
