<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPNaturesalarieCab2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.gTT0Rlo.App\Entity\PNaturesalarieCab' shared service.
     *
     * @return \App\Entity\PNaturesalarieCab
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.gTT0Rlo": it references class "App\\Entity\\PNaturesalarieCab" but no such service exists.');
    }
}
