<?php

namespace ContainerEOIwoaH;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsers5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.tTngChG.App\Entity\Users' shared service.
     *
     * @return \App\Entity\Users
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.tTngChG": it references class "App\\Entity\\Users" but no such service exists.');
    }
}
