<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMgXxIJj\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMgXxIJj/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMgXxIJj.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMgXxIJj\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMgXxIJj\App_KernelDevDebugContainer([
    'container.build_hash' => 'MgXxIJj',
    'container.build_id' => '73f0dbbe',
    'container.build_time' => 1695157277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMgXxIJj');
