<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYyc52x4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYyc52x4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYyc52x4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYyc52x4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYyc52x4\App_KernelDevDebugContainer([
    'container.build_hash' => 'Yyc52x4',
    'container.build_id' => '4814c100',
    'container.build_time' => 1699626387,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYyc52x4');
