<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'app' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_arr-effffa.js',
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_axios_index_js-node_m-ac4e4c.js',
                '/build/app.js',
            ],
            'css' => [
                '/build/vendors-node_modules_symfony_stimulus-bridge_dist_index_js-node_modules_axios_index_js-node_m-ac4e4c.css',
                '/build/app.css',
            ],
        ],
        'security_register' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_arr-effffa.js',
                '/build/security_register.js',
            ],
        ],
        'salarie_salarie' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_arr-effffa.js',
                '/build/salarie_salarie.js',
            ],
        ],
        'paie_bulletin' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_arr-effffa.js',
                '/build/paie_bulletin.js',
            ],
        ],
        'paie_honoraire' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors-node_modules_core-js_modules_es_array_for-each_js-node_modules_core-js_modules_es_arr-effffa.js',
                '/build/paie_honoraire.js',
            ],
        ],
    ],
],

]];
